apiVersion: v1
kind: Service
metadata:
  name: trio-nginx-service
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trio-nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx
  strategy:
    rollingUpdate:
      maxSurge: 20%
      maxUnavailable: 20%
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-container
        image: seethatgee/trio-deploy-nginx:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
